LendInvestApplicationTask/force-app/main/default/objects/Sms_Setting__mdt/Sms_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for SMS service</description>
    <label>Sms Setting</label>
    <pluralLabel>Sms Settings</pluralLabel>
</CustomObject>

LendInvestApplicationTask/force-app/main/default/objects/Sms_Setting__mdt/fields/AccountSID__c.field-meta.xml
<CustomField>
    <fullName>AccountSID__c</fullName>
    <description>Account SID from Twillio</description>
    <label>AccountSID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/Sms_Setting__mdt/fields/FromNumber__c.field-meta.xml
<CustomField>
    <fullName>FromNumber__c</fullName>
    <description>Twillio Account From Number</description>
    <label>FromNumber</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/Sms_Setting__mdt/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>Twillio Account Token</description>
    <label>Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/Sms_Setting__mdt/fields/ToNumber__c.field-meta.xml
<CustomField>
    <fullName>ToNumber__c</fullName>
    <description>Managers Number to send Gold Account Message.</description>
    <label>ManagerNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/classes/SmsSettings.cls
public class SmsSettings {

public static final Sms_Setting__mdt SMS_SETTING {
      get {
        if (SMS_SETTING == null) {
          SMS_SETTING = Sms_Setting__mdt.getInstance('TwillioSmsSetting');
        }
        return SMS_SETTING;
      }
      set;
    }
  
    public static final String MANAGERS_NUMBER {
      get {
        if (MANAGERS_NUMBER == null) {
          MANAGERS_NUMBER = SMS_SETTING.ToNumber__c;
        }
        return MANAGERS_NUMBER;
      }
      set;
    }
    
    public static final String FROM_NUMBER {
      get {
        if (FROM_NUMBER == null) {
          FROM_NUMBER = SMS_SETTING.FromNumber__c;
        }
        return FROM_NUMBER;
      }
      set;
    }
    
    public static final String ACCOUNT_SID {
      get {
        if (ACCOUNT_SID == null) {
          ACCOUNT_SID = SMS_SETTING.AccountSID__c;
        }
        return ACCOUNT_SID;
      }
      set;
    }
    
    public static final String TOKEN {
      get {
        if (TOKEN == null) {
          TOKEN = SMS_SETTING.Token__c;
        }
        return TOKEN;
      }
      set;
    }

}