LendInvestApplicationTask/force-app/main/default/objects/Account/fields/Customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Classification__c</fullName>
    <description>● GOLD = Total Customer Spend of £50,000 and above,
● SILVER = Total Customer Spend of £25,000 and above,
● BRONZE = Total Customer Spend of £10,000 and above,
● &lt;blank&gt; = Total Customer Spend is less than £10,000.</description>
    <formula>IF( Total_Customer_Spend__c &gt;= 50000, &quot;GOLD&quot;,
IF(Total_Customer_Spend__c &gt;= 25000 &amp;&amp; Total_Customer_Spend__c &lt;= 10000 ,&quot;SILVER&quot;, 
IF(Total_Customer_Spend__c &gt;= 10000 &amp;&amp; Total_Customer_Spend__c &lt;= 25000 ,&quot;BRONZE&quot;, 
&quot;&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Classification</label>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <description>Sum of the Amount of closed-won opportunities for an Account.</description>
    <label>Total Customer Spend</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/SMS_Log__c/SMS_Log__c.object-meta.xml
<CustomObject>
    <description>SMS log records to view SMS that have been sent</description>
    <label>SMS Log</label>
    <nameField>
        <label>SMS Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendInvestApplicationTask/force-app/main/default/objects/SMS_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account SMS message is associated to</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SMS Logs</relationshipLabel>
    <relationshipName>SMS_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/classes/AccountTriggerHandlerTest.cls
@IsTest
private class AccountTriggerHandlerTest {
    @IsTest
    private static void testupdateAccountGold_NotGold() {

        Account acc = new Account(name = 'New Account');
        insert acc;
        Map < Id, Account > oldAccounts = new Map <Id, Account> ([SELECT Customer_Classification__c, Id FROM Account WHERE Id =: Acc.id]);

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.StageName = 'Closed Won';
        opp.CloseDate = Date.today() + 1;
        opp.AccountId = acc.Id;
        opp.Amount = 1000;

        Insert opp;
 
        List <Account> accountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c FROM Account WHERE Id =: acc.Id];
        Test.startTest();
        AccountTriggerHandler.updateAccountGold(accountList, oldAccounts);
        Test.stopTest();

        for (Account account: accountList) {
            System.assertEquals(account.Customer_Classification__c, null, 'Customer Classification should be blank');
        }
    }

    @IsTest
    static void testupdateAccountGold_Gold() {
        Account acc = new Account(name = 'New Account');
        insert acc;
        Map <Id, Account> oldAccounts = new Map < Id, Account > ([SELECT Id, Customer_Classification__c, Name FROM Account WHERE Id =: Acc.id]);

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.StageName = 'Closed Won';
        opp.CloseDate = Date.today() + 1;
        opp.AccountId = acc.Id;
        opp.Amount = 60000;

        Insert opp;
        List <Sms_Log__c> smsLog = [select id, Account__c from SMS_Log__c where Account__c =: acc.id];
        
        List <Account> accountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c, Name FROM Account WHERE Id =: acc.Id];

        Test.setMock(HttpCalloutMock.class, new TwilioHttpCalloutMockClass());
        
        Test.startTest();

        AccountTriggerHandler.updateAccountGold(accountList, oldAccounts);
        Test.stopTest();

        for (Account account: accountList) {
            System.assertEquals(account.Customer_Classification__c, 'GOLD', 'Customer Classification should be GOLD');
        }
    }

    @IsTest
    static void newAccountGold_Gold() {

        Account acc = new Account(name = 'New Account');
        insert acc;
        Map <Id, Account > oldAccounts = new Map < Id, Account > ([SELECT Id, Customer_Classification__c, Name FROM Account WHERE Id =: Acc.id]);

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.StageName = 'Closed Won';
        opp.CloseDate = Date.today() + 1;
        opp.AccountId = acc.Id;
        opp.Amount = 60000;

        Insert opp;
        List <Sms_Log__c> smsLog = [select id, Account__c from SMS_Log__c where Account__c =: acc.id];
        system.debug(smsLog.size());
        System.assertEquals(smsLog.size(), 0, 'Should not have any sms is log');

        Set <Id> accountIds = new Set < Id > {acc.Id};
        Test.setMock(HttpCalloutMock.class, new TwilioHttpCalloutMockClass());

        Test.startTest();
        AccountTriggerHandler.newAccountGold(accountIds);
        Test.stopTest();

        List <Account> accountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c FROM Account WHERE Id =: acc.Id];
        for (Account account: accountList) {
            System.assertEquals(account.Customer_Classification__c, 'GOLD', 'Customer Classification should be GOLD');
        }
    }
    
    @IsTest
    static void newAccountGold_NotGold() {

        Account acc = new Account(name = 'New Account');
        insert acc;
        Map <Id, Account> oldAccounts = new Map < Id, Account > ([SELECT Id, Customer_Classification__c, Name FROM Account WHERE Id =: Acc.id]);

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.StageName = 'Closed Won';
        opp.CloseDate = Date.today() + 1;
        opp.AccountId = acc.Id;
        opp.Amount = 20000;

        Insert opp;

        Set <Id> accountIds = new Set < Id > {acc.Id};
        Test.setMock(HttpCalloutMock.class, new TwilioHttpCalloutMockClass());

        Test.startTest();
        AccountTriggerHandler.newAccountGold(accountIds);
        Test.stopTest();

        List <Account> accountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c FROM Account WHERE Id =: acc.Id];
        for (Account account: accountList) {
            System.assertNotEquals(account.Customer_Classification__c, 'GOLD', 'Customer Classification should not be GOLD');
        }
    }


}