LendInvestApplicationTask/force-app/main/default/objects/Account/fields/Customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Classification__c</fullName>
    <description>● GOLD = Total Customer Spend of £50,000 and above,
● SILVER = Total Customer Spend of £25,000 and above,
● BRONZE = Total Customer Spend of £10,000 and above,
● &lt;blank&gt; = Total Customer Spend is less than £10,000.</description>
    <formula>IF( Total_Customer_Spend__c &gt;= 50000, &quot;GOLD&quot;,
IF(Total_Customer_Spend__c &gt;= 25000 &amp;&amp; Total_Customer_Spend__c &lt;= 10000 ,&quot;SILVER&quot;, 
IF(Total_Customer_Spend__c &gt;= 10000 &amp;&amp; Total_Customer_Spend__c &lt;= 25000 ,&quot;BRONZE&quot;, 
&quot;&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Classification</label>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/Account/fields/Total_Customer_Spend__c.field-meta.xml
<CustomField>
    <fullName>Total_Customer_Spend__c</fullName>
    <description>Sum of the Amount of closed-won opportunities for an Account.</description>
    <label>Total Customer Spend</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Closed Won</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/classes/AccountTriggerTest.cls
@IsTest
public class AccountTriggerTest {

    @IsTest
    private static void testCreateNewAccount_NoStatus() {
        Account acc = new Account(name = 'New Account');

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.StageName = 'Closed Won';
        opp.CloseDate = Date.today() + 1;
        opp.AccountId = acc.Id;
        opp.Amount = 1000;

        Test.startTest();
        Insert opp; 
        Test.stopTest();
        
        List <Account> accountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c FROM Account WHERE Id =: acc.Id];

        for (Account account: accountList) {
            System.assertEquals(account.Customer_Classification__c, '', 'Customer Classification should be blank');
        }
    }

    @IsTest
    private static void testCreateNewAccount_BronzeStatus() {
        Account acc = new Account(name = 'New Account');

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.StageName = 'Closed Won';
        opp.CloseDate = Date.today() + 1;
        opp.AccountId = acc.Id;
        opp.Amount = 10000;

        Test.startTest();
        Insert opp; 
        Test.stopTest();

        List <Account> accountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c FROM Account WHERE Id =: acc.Id];

        for (Account account: accountList) {
            System.assertEquals(account.Customer_Classification__c, 'BRONZE', 'Customer Classification should be BRONZE');
        }
    }
    @IsTest
    private static void testCreateNewAccount_SilverStatus() {
        Account acc = new Account(name = 'New Account');

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.StageName = 'Closed Won';
        opp.CloseDate = Date.today() + 1;
        opp.AccountId = acc.Id;
        opp.Amount = 25000;

        Test.startTest();
        Insert opp; 
        Test.stopTest();

        List <Account> accountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c FROM Account WHERE Id =: acc.Id];

        for (Account account: accountList) {
            System.assertEquals(account.Customer_Classification__c, 'SILVER', 'Customer Classification should be SILVER');
        }
    }
    @IsTest
    private static void testCreateNewAccount_GoldStatus() {
        Account acc = new Account(name = 'New Account');

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpportunity';
        opp.StageName = 'Closed Won';
        opp.CloseDate = Date.today() + 1;
        opp.AccountId = acc.Id;
        opp.Amount = 50000;

        List <Account> oldAccountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c FROM Account WHERE Id =: acc.Id];

        Test.startTest();
        Insert opp;
        Test.stopTest();
        List < Account > accountList = [SELECT Id, Total_Customer_Spend__c, Customer_Classification__c FROM Account WHERE Id =: acc.Id];

        for (Account account: oldAccountList) {
            System.assertEquals(account.Customer_Classification__c, '', 'Customer Classification should be blank');
        }
        for (Account account: accountList) {
            System.assertEquals(account.Customer_Classification__c, 'GOLD', 'Customer Classification should be GOLD');
        }
    }

}