LendInvestApplicationTask/force-app/main/default/objects/Account/fields/Customer_Classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Classification__c</fullName>
    <description>● GOLD = Total Customer Spend of £50,000 and above,
● SILVER = Total Customer Spend of £25,000 and above,
● BRONZE = Total Customer Spend of £10,000 and above,
● &lt;blank&gt; = Total Customer Spend is less than £10,000.</description>
    <formula>IF( Total_Customer_Spend__c &gt;= 50000, &quot;GOLD&quot;,
IF(Total_Customer_Spend__c &gt;= 25000 &amp;&amp; Total_Customer_Spend__c &lt;= 10000 ,&quot;SILVER&quot;, 
IF(Total_Customer_Spend__c &gt;= 10000 &amp;&amp; Total_Customer_Spend__c &lt;= 25000 ,&quot;BRONZE&quot;, 
&quot;&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Classification</label>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/Account/fields/Gold_Alert_SMS_Sent__c.field-meta.xml
<CustomField>
    <fullName>Gold_Alert_SMS_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when Account has reached Gold Status</description>
    <label>Gold Alert SMS Sent</label>
    <type>Checkbox</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler {

    public static Boolean isFirstTime = true;

    public static void updateAccountGold(List <Account> accounts, Map <Id, Account> oldAccounts) {
        if (isFirstTime) {

            for (Account account: accounts) {
                Account oldAccount = oldAccounts.get(account.Id);
                if (account.Customer_Classification__c <> oldAccount.Customer_Classification__c &&
                    account.Customer_Classification__c == 'GOLD' && oldAccount.Customer_Classification__c != 'GOLD' &&
                    account.Gold_Alert_SMS_Sent__c == FALSE) {

                    TwillioHttpCallout.sendGoldAccountSmsToManager(account.Name, account.Id);
                }
            }
            isFirstTime = false;
        }
    }
    public static void newAccountGold(Set <Id> accountIds) {
        String accName;
        List <Account> accounts = new List <Account>([SELECT Customer_Classification__c, Gold_Alert_SMS_Sent__c, Name FROM Account WHERE Id IN: accountIds]);

        for (Account account: accounts) {
            if (account.Customer_Classification__c == 'GOLD' && account.Gold_Alert_SMS_Sent__c == FALSE) {
                TwillioHttpCallout.sendGoldAccountSmsToManager(account.Name, account.id);
            }
        }
    }
}