LendInvestApplicationTask/force-app/main/default/objects/Account/fields/Gold_Alert_SMS_Sent__c.field-meta.xml
<CustomField>
    <fullName>Gold_Alert_SMS_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when Account has reached Gold Status</description>
    <label>Gold Alert SMS Sent</label>
    <type>Checkbox</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/SMS_Log__c/SMS_Log__c.object-meta.xml
<CustomObject>
    <description>SMS log records to view SMS that have been sent</description>
    <label>SMS Log</label>
    <nameField>
        <label>SMS Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LendInvestApplicationTask/force-app/main/default/objects/SMS_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account SMS message is associated to</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SMS Logs</relationshipLabel>
    <relationshipName>SMS_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/SMS_Log__c/fields/From_Number__c.field-meta.xml
<CustomField>
    <fullName>From_Number__c</fullName>
    <description>Phone number the SMS was sent from</description>
    <label>From Number</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/SMS_Log__c/fields/SMS_Body__c.field-meta.xml
<CustomField>
    <fullName>SMS_Body__c</fullName>
    <description>Message body of SMS</description>
    <label>SMS Body</label>
    <type>TextArea</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/SMS_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status is Passed if accepted by Twillio otherwise Status is Failed</description>
    <label>Status</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/objects/SMS_Log__c/fields/To_Number__c.field-meta.xml
<CustomField>
    <fullName>To_Number__c</fullName>
    <description>SMS number text was sent to</description>
    <label>To Number</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

LendInvestApplicationTask/force-app/main/default/classes/TwillioHttpCallout.cls
public class TwillioHttpCallout {

    public static HttpResponse TwillioHttpCallout(String toNumber, String smsBody) {

        String accountSid = SmsSettings.ACCOUNT_SID;
        String token = SmsSettings.TOKEN;
        String fromNumber = SmsSettings.FROM_NUMBER;

        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndPoint('https://api.twilio.com/2010-04-01/Accounts/' + accountSid + '/SMS/Messages.json');
        req.setMethod('POST');
        req.setHeader('Accept-Charset', 'utf-8');

        req.setHeader('Content-Type', 'application/x-www-form-urlencoded');

        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(accountSid + ':' + token)));

        req.setBody('To=' + EncodingUtil.urlEncode(toNumber, 'UTF-8') + '&From=' + EncodingUtil.urlEncode(fromNumber, 'UTF-8') + '&Body=' + smsBody);
        HttpResponse res = http.send(req);

        if (res.getStatusCode() == 201) {
            System.debug(res.getBody());
        } else {
            System.debug('Error. Status :' + res.getStatusCode());
        }
        return res;
    }

    @AuraEnabled
    public static Map <String, Object> sendCustomSMS(String messageBody, String toNumber, String accountId) {
        try {
            String fromNumber = SmsSettings.FROM_NUMBER;
            HttpResponse res = TwillioHttpCallout.TwillioHttpCallout(toNumber, messageBody);

            Map <String, Object> resultsMap = (Map < String, Object > ) JSON.deserializeUntyped(res.getBody());
            String status = String.valueOf(resultsMap.get('status'));
            CheckSMSResponseSmsLog(accountId, toNumber, fromNumber, messageBody, status);

            return resultsMap;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @future(callout = true)
    public static void sendGoldAccountSmsToManager(String accountName, String accountId) {
        try {
            String toNumber = SmsSettings.MANAGERS_NUMBER;
            String smsBody = 'Great News! A customer has reached Gold. ' + accountName + ' will get VIP Treatment.';
            String fromNumber = SmsSettings.FROM_NUMBER;
            
            HttpResponse res = TwillioHttpCallout.TwillioHttpCallout(toNumber, smsBody);

            Map <String, Object> resultsMap = (Map <String, Object> ) JSON.deserializeUntyped(res.getBody());
            String status = String.valueOf(resultsMap.get('status'));
           
            CheckSMSResponseSmsLog(accountId, toNumber, fromNumber, smsBody, status);

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @TestVisible
    private static void checkSMSResponseSmsLog(String accountId, String toNum, String fromNum, String smsBody, String status) {
        List <Account> accs = new List <Account>();
        
        if (status == '200' || status == '201' || status == 'queued' || status == 'accepted') {
            insert new SMS_Log__c(Account__c = accountId, To_Number__c = toNum, From_Number__c = fromNum, SMS_Body__c = smsBody, status__c = 'Passed');
          
            accs = [SELECT Id, Gold_Alert_SMS_Sent__c, Name FROM Account WHERE Id =: accountId];
            for (Account a: accs) {
                if(a.Gold_Alert_SMS_Sent__c == FALSE){
                    a.Gold_Alert_SMS_Sent__c = TRUE;
                }
            }
        } else {
                insert new SMS_Log__c(Account__c = accountId, To_Number__c = toNum, From_Number__c = fromNum, SMS_Body__c = smsBody, status__c = 'Failed');
   	    }

        if(accs.size()>0){
            update accs;
        }
        
    }
}